export interface LearningDayRecord {
  date: string
  weekday: string
  duration: string
  track: string
  frontend: string[]
  ai: string[]
  minimum: string[]
  outputs: string[]
  status: string
}

export const learningArchiveData: LearningDayRecord[] = [
  {
    date: '2026-03-26',
    weekday: 'Thursday',
    duration: '1.5-2 小时',
    track: '前端求职修复线 + AI 应用认知线（六月底求职加速版）',
    frontend: [
      'Redux 基础认知：它主要解决什么问题',
      'store、action、reducer 的最小闭环',
      'Redux 为什么强调数据单向流动',
    ],
    ai: ['Agent 和 Tool Calling 的区别', '为什么说 Agent 更像“会拆步骤的执行者”'],
    minimum: ['1 个 Redux 闭环认知', '1 道状态管理题', '1 个 AI 概念区分点', '1 条自己的总结'],
    outputs: ['Redux 是什么？', 'store / action / reducer 分别是什么？'],
    status: '待开始',
  },
  {
    date: '2026-03-27',
    weekday: 'Friday',
    duration: '1.5-2 小时',
    track: '前端求职修复线 + AI 应用认知线（六月底求职加速版）',
    frontend: [
      'Zustand 和 Redux 的直观差别',
      '什么项目更适合轻量状态管理',
      '状态管理面试题初步口述',
    ],
    ai: ['MCP 是什么', '为什么它可以理解为模型和外部能力之间的协议层'],
    minimum: ['1 道状态管理对比题', '1 个选型理解点', '1 个 AI 协议概念点', '1 条自己的总结'],
    outputs: ['Redux 和 Zustand 最大差别是什么？', '什么场景更适合轻量状态管理？'],
    status: '待开始',
  },
  {
    date: '2026-03-28',
    weekday: 'Saturday',
    duration: '2-3 小时',
    track: '前端求职修复线 + AI 应用认知线（六月底求职加速版）',
    frontend: [
      '项目表达训练：选一个 React 项目，补全技术栈、业务场景、难点、优化点',
      '整理 1 个可用于面试的项目讲述版本',
    ],
    ai: ['Skill 是什么', 'Skill、Tool、Agent、MCP 在你的工作流里分别扮演什么角色'],
    minimum: ['1 版项目讲述', '1 个项目难点表达', '1 个 AI 工具链概念串联点', '1 条自己的总结'],
    outputs: [],
    status: '待开始',
  },
  {
    date: '2026-03-29',
    weekday: 'Sunday',
    duration: '2-3 小时',
    track: '前端求职修复线 + AI 应用认知线（六月底求职加速版）',
    frontend: ['本周复盘：组件通信、Context、状态管理、项目表达回顾', '口述 3-4 个本周前端问题'],
    ai: [
      '本周 AI 复盘：Prompt / Context / Tool Calling / Agent / MCP / Skill',
      '用自己的话重新讲一遍概念关系',
    ],
    minimum: ['复述 3 个前端点', '复述 3 个 AI 概念关系', '1 段本周总结'],
    outputs: [],
    status: '待开始',
  },
  {
    date: '2026-03-30',
    weekday: 'Monday',
    duration: '1.5-2 小时',
    track: '前端求职修复线 + AI 应用认知线（六月底求职加速版）',
    frontend: [
      'JavaScript：this 的 4 种常见绑定方式',
      '默认绑定、隐式绑定、显式绑定、new 绑定分别是什么',
      '箭头函数为什么没有自己的 this',
    ],
    ai: ['RAG 是什么', '为什么很多 AI 产品不会只靠模型裸答'],
    minimum: ['1 道 JS 高频题', '1 个 this 原理补丁', '1 个 AI 架构概念点', '1 条自己的总结'],
    outputs: ['this 指向怎么判断？', '箭头函数和普通函数在 this 上有什么区别？'],
    status: '已沉淀为页面',
  },
  {
    date: '2026-03-31',
    weekday: 'Tuesday',
    duration: '1.5-2 小时',
    track: '前端求职修复线 + AI 应用认知线（六月底求职加速版）',
    frontend: [
      '原型和原型链是什么',
      '__proto__、prototype、constructor 的关系',
      '为什么 JS 继承离不开原型链',
    ],
    ai: ['Embedding 是什么', '为什么做检索时通常需要向量化'],
    minimum: ['1 道 JS 高频题', '1 个原型链补丁', '1 个 AI 检索概念点', '1 条自己的总结'],
    outputs: ['原型链是什么？', 'prototype 和 __proto__ 有什么区别？'],
    status: '已沉淀为页面',
  },
  {
    date: '2026-04-01',
    weekday: 'Wednesday',
    duration: '1.5-2 小时',
    track: '前端求职修复线 + AI 应用认知线（六月底求职加速版）',
    frontend: ['深拷贝和浅拷贝的区别', '常见拷贝方式有哪些问题', '为什么面试里常追问引用类型'],
    ai: ['向量数据库是干嘛的', '它和普通数据库在 AI 场景中的差别'],
    minimum: ['1 道 JS 基础题', '1 个引用类型补丁', '1 个 AI 存储概念点', '1 条自己的总结'],
    outputs: ['深拷贝和浅拷贝的区别是什么？', '常见深拷贝方式有什么局限？'],
    status: '待开始',
  },
  {
    date: '2026-04-02',
    weekday: 'Thursday',
    duration: '1.5-2 小时',
    track: '前端求职修复线 + AI 应用认知线（六月底求职加速版）',
    frontend: ['防抖和节流是什么', '它们分别适合什么场景', '手写层面先建立思路'],
    ai: ['Function Calling 和传统接口调用有什么不同', '为什么它适合接外部能力'],
    minimum: ['1 道 JS 高频题', '1 个性能优化补丁', '1 个 AI 调用方式概念点', '1 条自己的总结'],
    outputs: ['防抖和节流的区别是什么？', '它们分别适合什么场景？'],
    status: '待开始',
  },
  {
    date: '2026-04-03',
    weekday: 'Friday',
    duration: '1.5-2 小时',
    track: '前端求职修复线 + AI 应用认知线（六月底求职加速版）',
    frontend: [
      'Promise 的基本状态和链式调用',
      'then、catch、finally 分别做什么',
      '为什么异步编程离不开 Promise',
    ],
    ai: ['多模态是什么', '为什么模型不再只处理文本'],
    minimum: ['1 道 JS 高频题', '1 个 Promise 补丁', '1 个多模态概念点', '1 条自己的总结'],
    outputs: ['Promise 有哪些状态？', 'then 和 catch 的链式执行怎么理解？'],
    status: '待开始',
  },
  {
    date: '2026-04-04',
    weekday: 'Saturday',
    duration: '2-3 小时',
    track: '前端求职修复线 + AI 应用认知线（六月底求职加速版）',
    frontend: [
      'async / await 和 Promise 的关系',
      '为什么 async / await 让异步代码更容易读',
      '补一轮 Promise / async await 口述训练',
    ],
    ai: ['模型上下文窗口是什么', '为什么会有限制'],
    minimum: [
      '1 道异步编程题',
      '1 个 async / await 补丁',
      '1 个上下文窗口概念点',
      '1 条自己的总结',
    ],
    outputs: ['async / await 和 Promise 的关系是什么？', '为什么 await 看起来像同步代码？'],
    status: '待开始',
  },
  {
    date: '2026-04-05',
    weekday: 'Sunday',
    duration: '2-3 小时',
    track: '前端求职修复线 + AI 应用认知线（六月底求职加速版）',
    frontend: [
      '本周复盘：this、原型链、拷贝、防抖节流、Promise、async / await',
      '口述 3-4 个 JS 高频题',
    ],
    ai: ['本周 AI 复盘：RAG、Embedding、向量数据库、Function Calling、多模态、上下文窗口'],
    minimum: ['复述 3 个 JS 点', '复述 3 个 AI 概念关系', '1 段本周总结'],
    outputs: [],
    status: '待开始',
  },
  {
    date: '2026-04-06',
    weekday: 'Monday',
    duration: '1.5-2 小时',
    track: '前端求职修复线 + AI 应用认知线（六月底求职加速版）',
    frontend: [
      '浏览器缓存：强缓存和协商缓存是什么',
      'Cache-Control、Expires、ETag、Last-Modified 的作用',
      '为什么缓存是性能优化高频点',
    ],
    ai: ['推理模型和普通生成模型有什么差别', '为什么“会推理”会影响用户体验'],
    minimum: ['1 道浏览器高频题', '1 个缓存补丁', '1 个模型能力概念点', '1 条自己的总结'],
    outputs: ['强缓存和协商缓存的区别是什么？', 'ETag 和 Last-Modified 有什么区别？'],
    status: '待开始',
  },
  {
    date: '2026-04-07',
    weekday: 'Tuesday',
    duration: '1.5-2 小时',
    track: '前端求职修复线 + AI 应用认知线（六月底求职加速版）',
    frontend: ['跨域是什么', '为什么浏览器里会有同源策略', '常见跨域方案有哪些'],
    ai: ['AI 产品里的延迟为什么重要', '首字时间、总耗时、流式体验分别影响什么'],
    minimum: ['1 道浏览器高频题', '1 个跨域补丁', '1 个 AI 体验指标点', '1 条自己的总结'],
    outputs: ['什么是跨域？', '常见跨域方案有哪些？'],
    status: '待开始',
  },
  {
    date: '2026-04-08',
    weekday: 'Wednesday',
    duration: '1.5-2 小时',
    track: '前端求职修复线 + AI 应用认知线（六月底求职加速版）',
    frontend: ['重排和重绘是什么', '哪些操作更容易触发重排', '为什么性能优化经常提它们'],
    ai: ['为什么 AI 产品常用流式 + 历史记录 + 工具调用的组合', '从产品视角做一次串联'],
    minimum: ['1 道浏览器性能题', '1 个渲染补丁', '1 个 AI 产品串联点', '1 条自己的总结'],
    outputs: ['重排和重绘的区别是什么？', '为什么重排成本通常更高？'],
    status: '待开始',
  },
  {
    date: '2026-04-09',
    weekday: 'Thursday',
    duration: '1.5-2 小时',
    track: '前端求职修复线 + AI 应用认知线（六月底求职加速版）',
    frontend: [
      'Webpack 是什么',
      '它在前端工程化里主要负责什么',
      'entry、output、loader、plugin 的最小认知',
    ],
    ai: ['AI Agent 产品里前端为什么不只是“做页面”', '从交互、状态、可视化、工具结果承接角度理解'],
    minimum: ['1 道工程化高频题', '1 个 Webpack 基础补丁', '1 个 AI 前端职责点', '1 条自己的总结'],
    outputs: ['Webpack 是什么？', 'loader 和 plugin 的区别是什么？'],
    status: '待开始',
  },
  {
    date: '2026-04-10',
    weekday: 'Friday',
    duration: '1.5-2 小时',
    track: '前端求职修复线 + AI 应用认知线（六月底求职加速版）',
    frontend: [
      'Webpack 和 Vite 的差别',
      '为什么 Vite 在开发阶段更快',
      '什么时候仍然需要理解 Webpack',
    ],
    ai: ['模型输出为什么会不稳定', '提示词、上下文、采样策略会怎样影响结果'],
    minimum: [
      '1 道工程化对比题',
      '1 个构建工具选型点',
      '1 个模型输出稳定性概念点',
      '1 条自己的总结',
    ],
    outputs: ['Webpack 和 Vite 最大差别是什么？', '为什么 Vite 开发体验通常更快？'],
    status: '待开始',
  },
  {
    date: '2026-04-16',
    weekday: 'Thursday',
    duration: '1.5-2 小时',
    track: '前端求职修复线 + AI 应用认知线（六月底求职加速版）',
    frontend: ['联合类型、交叉类型、类型守卫是什么', '为什么 TypeScript 不是只会“标类型”'],
    ai: ['为什么前端接 AI 输出时需要校验和兜底', '从不稳定输出到可展示数据的转换思路'],
    minimum: ['1 道 TS 高频题', '1 个类型判断补丁', '1 个前端接 AI 输出的工程点', '1 条自己的总结'],
    outputs: ['联合类型和交叉类型的区别是什么？', '类型守卫是干嘛的？', '写出一段 AI 输出校验理解'],
    status: '已沉淀为页面',
  },
  {
    date: '2026-04-17',
    weekday: 'Friday',
    duration: '1.5-2 小时',
    track: '前端求职修复线 + AI 应用认知线（六月底求职加速版）',
    frontend: [
      'tsconfig 是做什么的',
      '为什么模块解析、目标版本、严格模式会影响项目开发',
      '建立 TS 工程配置认知',
    ],
    ai: ['为什么 AI 产品常需要可观测性', '日志、失败重试、工具结果展示为什么重要'],
    minimum: ['1 个 TS 工程配置点', '1 道类型系统题', '1 个 AI 工程观念点', '1 条自己的总结'],
    outputs: ['tsconfig 是干嘛的？', 'strict 模式为什么重要？', '写出一段 AI 可观测性理解'],
    status: '已沉淀为页面',
  },
]

export const learningArchiveMap = Object.fromEntries(
  learningArchiveData.map((item) => [item.date, item])
)
